# Generated by Django 5.1.6 on 2025-03-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/default.jpg', upload_to='thumbnails/'),
        ),
    ]
